api_settings:
  base_url: https://stats.data.gouv.fr/
  url_parameters:
    expanded: 1
    format: JSON
    token_auth: anonymous
    idSite: 150
    filter_limit: -1
    module: API
    period: day
  start_date: 2021-01-20
  end_date: 2021-01-21
# Specify database provider
db_settings:
  db_provider: sqlite3
  db_name: database
# Specify requests to be made in order to set the database properly
requests:
  visits:
    url_parameters:
      method: API.get
      format_metrics: 1
    need_transpose: True
    index_column_new_name: date
  pages:
    url_parameters:
      method: Actions.getPageUrls
      flat: 1
    date_range: True
  referrers:
    url_parameters:
      method: Referrers.getReferrerType
      format_metrics: 1
    date_range: True
